Repository JNU-econovation/Lean-FE, pull requests merged in 2025-01, with the labels that each got.

#4 [FEAT] 컴포넌트 추가 #1
  src/components/Button/Button.css
  src/components/Button/Button.jsx
  src/components/Dropdown/SignupDropdown.css
  src/components/Dropdown/SignupDropdown.jsx
  src/components/Input/SigninInput.css
  src/components/Input/SigninInput.jsx
  src/components/Input/SignupInput.css
  src/components/Input/SignupInput.jsx
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
Labels: ✨ Feature

#6 [FEAT] 회원가입 페이지 추가 #3
  src/hooks/useSignupValidation.js
  src/pages/Signup/Signup.css
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupAcademicStep.jsx
  src/pages/Signup/SignupCompleteStep.jsx
  src/pages/Signup/SignupIDStep.jsx
  src/pages/Signup/SignupProfileStep.jsx
Labels: ✨ Feature

#8 [FEAT] 메인 페이지 추가 #7
  src/components/Card/MainCard.css
  src/components/Card/MainCard.jsx
  src/index.css
  src/pages/Main/Main.css
  src/pages/Main/Main.jsx
  src/pages/Signup/Signup.css
Labels: ✨ Feature

#9 [Design] Main 관련 자잘한 변경
  src/components/Card/MainCard.css
  src/pages/Main/Main.css
  src/pages/Main/Main.jsx
Labels: ✨ Feature

#13 [Style] Css 스타일 변경 #12
  src/components/Card/MainCard.css
  src/components/Card/MainCard.jsx
  src/components/Input/SigninInput.css
  src/components/Input/SigninInput.jsx
  src/components/Input/SignupInput.css
  src/components/Input/SignupInput.jsx
  src/components/Navigation/Navigation.css
  src/components/Navigation/Navigation.jsx
  src/pages/Main/Main.css
  src/pages/Main/Main.jsx
  src/pages/Signup/Signup.css
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupAcademicStep.jsx
  src/pages/Signup/SignupCompleteStep.jsx
  src/pages/Signup/SignupIDStep.jsx
  src/pages/Signup/SignupProfileStep.jsx
  src/styles/Style.css
Labels: 🔨 Refactor

#16 [FEAT] 대여정보 페이지 추가 #14
  src/App.jsx
  src/components/Card/ItemRentalStateCard.css
  src/components/Card/ItemRentalStateCard.jsx
  src/components/Card/MainCard.css
  src/components/Card/MainCard.jsx
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.jsx
  src/components/Navtab/Navtab.css
  src/components/Navtab/Navtab.jsx
  src/index.css
  src/pages/Main/Main.jsx
  src/pages/Main/MyPage.jsx
  src/pages/RentalInfo/RentalInfo.css
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/Signup/SignupAcademicStep.jsx
  src/pages/Signup/SignupIDStep.jsx
  src/pages/Signup/SignupProfileStep.jsx
Labels: ✨ Feature

#19 [STYLE] css module 추가 #18
  src/App.jsx
  src/components/Card/ItemRentalStateCard.jsx
  src/components/Card/ItemRentalStateCard.module.css
  src/components/Card/MainCard.jsx
  src/components/Card/MainCard.module.css
  src/components/Dropdown/SignupDropdown.jsx
  src/components/Dropdown/SignupDropdown.module.css
  src/components/Input/SigninInput.jsx
  src/components/Input/SigninInput.module.css
  src/components/Input/SignupInput.jsx
  src/components/Input/SignupInput.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/components/Navtab/Navtab.jsx
  src/components/Navtab/Navtab.module.css
  src/pages/Main/Main.jsx
  src/pages/Main/Main.module.css
  src/pages/Main/MyPage.jsx
  src/pages/Main/MyPage.module.css
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/RentalInfo/RentalInfo.module.css
  src/pages/Signin/Signin.jsx
  src/pages/Signin/Signin.module.css
  src/pages/Signup/Signup.jsx
  src/pages/Signup/Signup.module.css
  src/pages/Signup/SignupAcademicStep.jsx
  src/pages/Signup/SignupCompleteStep.jsx
  src/pages/Signup/SignupIDStep.jsx
  src/pages/Signup/SignupProfileStep.jsx
  src/styles/Style.css
Labels: 🔨 Refactor

#20 [FEAT] 세부 정보 확인 페이지 추가 #17
  src/components/Badge/RentalStatusBadge.jsx
  src/components/Badge/RentalStatusBadge.module.css
  src/components/Box/ItemInfoBox.jsx
  src/components/Box/ItemInfoBox.module.css
  src/components/Box/RentalInfoBox.jsx
  src/components/Box/RentalInfoBox.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/pages/RentalInfo/RentalInfoDetail.jsx
  src/pages/RentalInfo/RentalInfoDetail.module.css
Labels: ✨ Feature

#21 [FEAT] 물품 반납 페이지 추가 #015
  src/App.jsx
  src/components/Card/ItemRentalStateCard.jsx
  src/components/Card/ItemRentalStateCard.module.css
  src/components/Navtab/Navtab.jsx
  src/pages/Main/Main.jsx
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/ReturnRequest/ReturnRequest.jsx
  src/pages/ReturnRequest/ReturnRequest.module.css
  src/pages/Signup/Signup.module.css
  src/pages/Signup/SignupAcademicStep.jsx
  src/pages/Signup/SignupCompleteStep.jsx
  src/pages/Signup/SignupIDStep.jsx
  src/pages/Signup/SignupProfileStep.jsx
  src/styles/Style.css
Labels: ✨ Feature

#22 Design : 반납신청 하단 버튼 디자인 조금 수정
  src/pages/ReturnRequest/ReturnRequest.jsx
  src/pages/ReturnRequest/ReturnRequest.module.css
Labels: ✨ Feature

#26 [FEAT] 물품 대여 화면 추가 #25
  src/App.jsx
  src/components/Box/StudentCouncilList.jsx
  src/components/Box/StudentCouncilList.module.css
  src/components/Navbar/Navbar.jsx
  src/components/Navbar/Navbar.module.css
  src/components/Navtab/Navtab.module.css
  src/pages/Main/Main.jsx
  src/pages/RentalInfo/RentalInfoDetail.jsx
  src/pages/RentalItem/RentalItem.jsx
  src/pages/RentalItem/RentalItem.module.css
  src/pages/ReturnRequest/ReturnRequest.jsx
Labels: ✨ Feature

#27 [FIX] 일부 화면 조정
  src/components/Box/StudentCouncilList.module.css
  src/pages/ReturnRequest/ReturnRequest.module.css
Labels: 🐞 BugFix

#29 [FEAT] 대여 물품 선택 페이지 추가 #28
  src/App.jsx
  src/components/Card/ItemCard.jsx
  src/components/Card/ItemCard.module.css
  src/components/Card/ItemRentalStateCard.jsx
  src/components/Card/ItemRentalStateCard.module.css
  src/pages/RentalItem/RentalItem.jsx
  src/pages/RentalItem/RentalItem.module.css
  src/pages/RentalItem/RentalItemSelect.jsx
  src/pages/RentalItem/RentalItemSelect.module.css
  src/styles/Style.css
Labels: ✨ Feature

#31 [FEAT] 대여 시간 선택 화면 추가 #30
  package-lock.json
  package.json
  src/App.jsx
  src/components/DatePicker/CustomDatePicker.jsx
  src/components/DatePicker/CustomDatePicker.module.css
  src/components/DatePicker/CustomInput.jsx
  src/components/DatePicker/CustomInput.module.css
  src/pages/RentalItem/RentalItemComplete.jsx
  src/pages/RentalItem/RentalItemComplete.module.css
  src/pages/RentalItem/RentalItemSelect.jsx
  src/pages/RentalItem/RentalTimeSelect.jsx
  src/pages/RentalItem/RentalTimeSelect.module.css
Labels: ✨ Feature

#33 [FEAT] (관리자) 관리 물품 선택 페이지 추가 #32
  package-lock.json
  package.json
  src/App.jsx
  src/components/Fab/ItemFab.jsx
  src/components/page/CompletePage.jsx
  src/components/page/CompletePage.module.css
  src/components/page/MainPage.jsx
  src/components/page/MainPage.module.css
  src/pages/Main/Main.jsx
  src/pages/Main/MainAdmin.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItem.module.css
  src/pages/RentalItem/RentalItemComplete.jsx
  src/pages/ReturnRequest/ReturnRequestComplete.jsx
  src/pages/ReturnRequest/ReturnRequestComplete.module.css
  src/pages/Signin/Signin.jsx
  src/pages/Signup/Signup.module.css
  src/pages/Signup/SignupCompleteStep.jsx
Labels: ✨ Feature

#38 [FEAT] 물품 추가 및 삭제 페이지 구현 #34
  src/App.jsx
  src/components/Dialog/ConfirmDialog.jsx
  src/components/Fab/ItemFab.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItem.module.css
  src/pages/ManageItem/ManageItemAdd.jsx
  src/pages/ManageItem/ManageItemAdd.module.css
  src/pages/ManageItem/ManageItemDelete.jsx
  src/pages/RentalItem/RentalItem.module.css
  src/pages/RentalItem/RentalItemSelect.module.css
  src/pages/RentalItem/RentalTimeSelect.module.css
  src/pages/Signup/Signup.module.css
Labels: ✨ Feature

#39 [FEAT] 물품 정보 페이지 구현 #35
  src/App.jsx
  src/components/Navbar/Navbar.jsx
  src/components/page/ItemAddEdit.jsx
  src/components/page/ItemAddEdit.module.css
  src/components/page/MainPage.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItemAdd.jsx
  src/pages/ManageItem/ManageItemEdit.jsx
  src/pages/ManageItem/ManageItemInfo.jsx
  src/pages/ManageItem/ManageItemInfo.module.css
Labels: ✨ Feature

#43 [FEAT] apiClient 구현 #42
  .gitignore
  package-lock.json
  package.json
  src/pages/Signin/Signin.jsx
  src/services/apiClient.jsx
Labels: ✨ Feature

#57 [FEAT] 메인화면에서 사용자 정보 불러오기
  src/components/page/MainPage.jsx
  src/constants/userId.js
Labels: ✨ Feature

#59 feat: 마이페이지 사용자 정보 불러오기 기능 구현
  src/constants/userId.js
  src/pages/Main/MyPage.jsx
Labels: ✨ Feature

#61 [FEAT] 물품 대여시 총학생회 + 본인이 속한 학생회 불러오는기능 추가 #50
  src/pages/RentalItem/RentalItem.jsx
Labels: ✨ Feature

#62 [FEAT] 특정 학생회 대여물품 가져오기 #51
  src/pages/RentalItem/RentalItem.jsx
  src/pages/RentalItem/RentalItemSelect.jsx
Labels: ✨ Feature

#63 [FEAT] 사용자 대여 정보 및 세부 정보 확인 #48
  src/components/Badge/RentalStatusBadge.jsx
  src/components/Card/ItemRentalStateCard.jsx
  src/components/Card/ItemRentalStateCard.module.css
  src/components/Navtab/Navtab.jsx
  src/constants/rentalStatus.js
  src/hooks/dateFormatChange.js
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/RentalItem/RentalItemSelect.jsx
  src/pages/RentalItem/RentalTimeSelect.jsx
Labels: ✨ Feature

#65 [FIX] 학생회용 main 페이지 들어온 요청 기능 버그 수정
  src/components/page/MainPage.jsx
  src/constants/rentalStatus.js
Labels: 🐞 BugFix

#66 [FEAT] 물건 예약 기능
  .gitignore
  src/constants/userId.js
  src/pages/RentalItem/RentalTimeSelect.jsx
Labels: ✨ Feature

#67 [FEAT] 메인 화면에서 사용자 대여 상태에 따라 대여 가능 화면 분기 처리 #58
  src/components/page/MainPage.jsx
  src/components/page/MainPage.module.css
Labels: ✨ Feature

#68 [FEAT] 사용자 반납신청
  src/pages/Main/MyPage.jsx
  src/pages/ReturnRequest/ReturnRequest.jsx
Labels: ✨ Feature

#69 [FEAT] 사용자 대여 정보 및 세부 정보 확인 #48
  src/components/Box/RentalInfoBox.jsx
  src/components/Box/RentalInfoBox.module.css
  src/components/page/MainPage.jsx
  src/constants/rentalStatus.js
  src/hooks/dateFormatChange.js
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/RentalInfo/RentalInfoDetail.jsx
Labels: ✨ Feature

#71 [FEAT] 회원가입 기능 #45
  src/components/Dropdown/SignupDropdown.jsx
  src/components/page/MainPage.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupAcademicStep.jsx
  src/pages/Signup/SignupIDStep.jsx
  src/pages/Signup/SignupProfileStep.jsx
Labels: ✨ Feature

#73 BugFix: 반납신청 페이지 '만료', '대여중'일때 필터링
  src/pages/ReturnRequest/ReturnRequest.jsx
Labels: 🐞 BugFix

#74 [FEAT] 학생회 대여 물품 추가 삭제 기능
  src/components/page/ItemAddEdit.jsx
  src/components/page/MainPage.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItemDelete.jsx
  src/pages/ReturnRequest/ReturnRequest.jsx
Labels: ✨ Feature

#75 [FEAT] 대여 물품 총량 수정 기능
  src/components/page/ItemAddEdit.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItemAdd.jsx
  src/pages/ManageItem/ManageItemEdit.jsx
  src/pages/ManageItem/ManageItemInfo.jsx
Labels: ✨ Feature

#76 [FEAT] 학생회 대여 리스트 조회 기능, 세부 정보 확인 기능 #54
  src/components/Box/RentalInfoBox.jsx
  src/components/Box/RentalInfoBox.module.css
  src/components/Box/StudentInfoBox.jsx
  src/components/Dialog/ConfirmDialog.jsx
  src/components/page/ItemAddEdit.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItemDelete.jsx
  src/pages/ManageItem/ManageItemInfo.jsx
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/ReservationInfo/ReservationInfo.jsx
  src/pages/ReservationInfo/ReservationInfoDetail.jsx
Labels: ✨ Feature

#79 [FEAT] 로그인 기능 구현 #78
  package-lock.json
  package.json
  src/App.jsx
  src/components/Navbar/Navbar.jsx
  src/components/page/MainPage.jsx
  src/hooks/userContext.jsx
  src/hooks/userProvider.jsx
  src/pages/Main/Main.jsx
  src/pages/Main/MainAdmin.jsx
  src/pages/Main/MyPage.jsx
  src/pages/ManageItem/ManageItem.jsx
  src/pages/ManageItem/ManageItemAdd.jsx
  src/pages/ManageItem/ManageItemDelete.jsx
  src/pages/ManageItem/ManageItemInfo.jsx
  src/pages/RentalInfo/RentalInfo.jsx
  src/pages/RentalItem/RentalItem.jsx
  src/pages/RentalItem/RentalTimeSelect.jsx
  src/pages/ReservationInfo/ReservationInfo.jsx
  src/pages/ReservationInfo/ReservationInfoDetail.jsx
  src/pages/ReturnRequest/ReturnRequest.jsx
  src/pages/Signin/Signin.jsx
Labels: ✨ Feature

#80 [FEAT] 추가 페이지 및 기본 이미지 설정 #77
  src/assets/로토스.jpeg
  src/assets/크리스피롤.jpg
  src/assets/포테이토크리스프.jpg
  src/components/Box/ItemInfoBox.jsx
  src/components/Box/ItemInfoBox.module.css
  src/components/Box/StudentCouncilList.jsx
  src/components/Box/StudentCouncilList.module.css
  src/components/Card/ItemCard.jsx
  src/components/Card/ItemCard.module.css
  src/components/Card/ItemRentalStateCard.jsx
  src/components/Card/ItemRentalStateCard.module.css
  src/components/ImageBox/ImageBox.jsx
  src/pages/ManageItem/ManageItemInfo.jsx
  src/pages/ManageItem/ManageItemInfo.module.css
  src/pages/RentalItem/RentalTimeSelect.jsx
  src/pages/RentalItem/RentalTimeSelect.module.css
  src/styles/Style.css
Labels: ✨ Feature

#82 [FEAT] 폰트 수정 #81
  index.html
  src/components/Box/ItemInfoBox.module.css
  src/components/Box/RentalInfoBox.module.css
  src/components/Box/StudentInfoBox.module.css
  src/components/Card/ItemCard.module.css
  src/components/Card/ItemRentalStateCard.module.css
  src/components/Card/MainCard.module.css
  src/components/Navbar/Navbar.module.css
  src/components/Navtab/Navtab.module.css
  src/components/page/CompletePage.module.css
  src/components/page/MainPage.module.css
  src/index.css
  src/pages/ManageItem/ManageItem.module.css
  src/pages/ManageItem/ManageItemInfo.module.css
  src/pages/RentalItem/RentalTimeSelect.module.css
  src/pages/Signup/Signup.module.css
Labels: ✨ Feature

#84 [FIX] datepicker 오늘 이전 날짜 선택 안되도록 수정
  src/components/DatePicker/CustomDatePicker.jsx
  src/components/DatePicker/CustomDatePicker.module.css
Labels: 🐞 BugFix

#85 feat: logo change
  public/favicon.svg
Labels: ✨ Feature

#86 feat: 로고 재수정
  public/favicon.svg
Labels: ✨ Feature
